In [29]:
import pandas as pd
import glob

In [30]:
saved_path = "D:\\code\\proj_ml\\ML_Project\\data\\saved"
saved_files = glob.glob(saved_path + "/*.csv")

In [31]:
gold_file = [f for f in saved_files if 'gold' in f][0]
merged_df = pd.read_csv(gold_file)
merged_df['Date'] = pd.to_datetime(merged_df['Date'])

for file in saved_files:
    if 'gold' not in file:
        df = pd.read_csv(file)
        df['Date'] = pd.to_datetime(df['Date'])
        merged_df = pd.merge(merged_df, df, on='Date', how='left')

# Save the final merged DataFrame
merged_df.to_csv(f"{saved_path}\\merged_data.csv", index=False)

In [32]:
merged_df.head()

,Date,gold_open,gold_high,gold_low,gold_close,copper,crude_oil,DXY,EURUSD,MSCI,NASDAQ,NLR,platinum,RUT,silver,SP500,VIX
0,2024-05-20,2422.2,2454.2,2411.1,2438.5,5.0790,79.30,104.57,1.0857,512.26,16794.87,88.50,1063.7,2102.50,32.426,5308.13,12.15
1,2024-05-17,2381.4,2427.4,2377.8,2417.4,5.0500,79.58,104.45,1.0871,505.33,16685.97,87.39,1090.0,2095.72,31.259,5303.27,11.99
2,2024-05-16,2391.5,2402.7,2375.2,2385.5,4.8770,79.23,104.46,1.0869,497.51,16698.32,85.22,1071.3,2096.25,29.876,5297.10,12.42
3,2024-05-15,2362.9,2396.1,2357.1,2394.9,4.9245,78.63,104.35,1.0885,490.06,16742.39,85.26,1070.1,2109.46,29.729,5308.15,12.45
4,2024-05-14,2342.3,2365.2,2340.5,2359.9,4.8950,78.02,105.01,1.0820,488.11,16511.18,84.06,1044.6,2085.69,28.702,5246.68,13.42

In [33]:
merged_df.isnull().sum()

Date          0
gold_open     0
gold_high     0
gold_low      0
gold_close    0
copper        0
crude_oil     0
DXY           0
EURUSD        0
MSCI          0
NASDAQ        0
NLR           0
platinum      0
RUT           0
silver        0
SP500         0
VIX           0
dtype: int64